### ISSUE TITLE
Proper dependency tracking

### ISSUE THREAD

**Issue by jharmison-redhat** [RedHatGov/devsecops-workshop-code#7]
As we have intentionally not used `meta/main.yml` for `dependencies`, we should implement some mechanism for proper dependency mapping with clear and obvious mechanisms for the toggles. @posip-redhat recommended tiers of toggles to bring more clarity. I have constructed a small example that needs some work here:

```
components:
- name: codeready_workspaces
  deploy: true
- name: workshop_dashboard
  deploy: true
  dependencies:
  - codeready_workspaces
- name: quay
  deploy: true
  - rh-sso
- name: gitea
  deploy: true
  dependencies:
  - rh-sso
- name: sonarqube
  deploy: true
  dependencies:
  - rh-sso
- name: tekton
  deploy: true
- name: tekton-pipelines
  deploy: true
  dependencies:
  - tekton
  - gitea
  - sonarqube
```

In the event that a component of the workshop is set to `deploy: true`, then all dependencies could be mapped back against the `components` list and filtered where the `name` matches to validate that deployment toggle. This could be a single validate loop through the variable, and could be achieved in a single step with a list-style `when` block on a `fail` module.

Pros:
1. exposes the dependencies to the user of the toggles
2. provides a mechanism to pre-validate configuration

Cons:
1. This has the dependencies in the same place as the toggles, so an enterprising user could just..... remove that dependency, thinking it's the right thing. We could mitigate this by recreating this list without the `deploy` key in a variable embedded into a playbook and using that for dependency tracking, but then there's two places to update the dependencies when a code patch change causes such a thing.

I think the most elegant way to solve this still eludes me, so I haven't started it yet :)
